# ============================================================
# FutbotMX — hostapd.conf
# AP WiFi en wlan0 (chipset Broadcom brcmfmac — driver nl80211)
# ============================================================

interface=wlan0
driver=nl80211

# ── Red ───────────────────────────────────────────────────────
ssid=RPI_INET
ignore_broadcast_ssid=1       # SSID oculto — robot2 lo conoce explícitamente

# ── Radio 2.4 GHz ─────────────────────────────────────────────
hw_mode=g
channel=6

# ── Seguridad WPA2-PSK ────────────────────────────────────────
wpa=2
wpa_passphrase=futbot2025
wpa_key_mgmt=WPA-PSK
rsn_pairwise=CCMP

# ── Estabilidad ───────────────────────────────────────────────
# Mantiene el AP activo aunque no haya clientes conectados
ap_isolate=0